# Generated by Django 5.2 on 2025-05-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ufr', models.CharField(choices=[('High-Tech', 'High-Tech'), ('Economie', 'Économie'), ('Droit', 'Droit'), ('Lettres', 'Lettres')], default='High-Tech', max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
