# Generated by Django 5.2 on 2025-05-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0002_filiere_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coordonateur',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.ufr'),
        ),
    ]
