# Generated by Django 5.2 on 2025-05-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0003_ufr_alter_coordonateur_ufr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.classe')),
                ('coordonateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.coordonateur')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.filiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
            ],
        ),
    ]
