# Generated by Django 5.2.1 on 2025-05-11 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ufr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UFR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.classe')),
                ('coordonateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.coordonateur')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.filiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
            ],
        ),
        migrations.AddField(
            model_name='coordonateur',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.ufr'),
        ),
    ]
