# Generated by Django 5.2.1 on 2025-05-11 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='coordonateur',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salle',
            name='etat',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée')], default='libre', max_length=10),
        ),
    ]
