# Generated by Django 5.2.1 on 2025-05-13 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0002_remove_reservation_coordonateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_fin',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='jour',
            field=models.CharField(default='Lundi', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
