# Generated by Django 5.2.1 on 2025-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0003_reservation_heure_debut_reservation_heure_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='est_occupe',
            field=models.BooleanField(default=True),
        ),
    ]
