# Generated by Django 5.2.1 on 2025-05-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0004_reservation_est_occupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='coordonnateur',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='salle.coordonateur'),
            preserve_default=False,
        ),
    ]
