# Generated by Django 5.2.1 on 2025-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0009_alter_reservation_coordonnateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='est_annule',
            field=models.BooleanField(default=False),
        ),
    ]
